# site settings
title: Yu.Jung
subtitle: dldbwjd7579.github.io/blog/
email: dldbwjd7579@gmail.com
description: Hi :)
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: 
author:
street_address: 
city: Seoul
state: 
zip_code: 
country: South Korea
phone: 

# homepage tiles
tiles-source: portfolio # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
instagram_url: https://www.instagram.com/msoyj/?hl=ko
linkedin_url: 
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
